name: CI - Assemble Debug

on:
  push:
    branches: [ main, "release/**", "feat/**", "chore/**", "docs/**" ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  assemble-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "apiKey=${{ secrets.GEMINI_API_KEY }}" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Debug
        run: ./gradlew --no-daemon :app:assembleDebug
        
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        if: github.ref == 'refs/heads/main'
        with:
          gradle-executable: ./gradlew
